### ISSUE TITLE
Tile KFind and System Settings modules.

### ISSUE THREAD

**Issue by Kharacternyk** [kwin-scripts/kwin-tiling#170] opened 2019-07-06 19:01 UTC
Hi. Great work so far, can't live without it since tried the first time!

Is it intended that KFind and System Settings **modules** (System Settings itself is tiled) float? I want them to be tiled as well as other windows, but I can't find the place in the code where these specific apps are mentioned. My custom list of floaters is empty.

**Comment by faho** [comment] 2019-07-06 19:19
>System Settings modules (System Settings itself is tiled) float?

These are basically dialogs, and they *should* float. We let every "transient" window float.

Likewise, kfind sets itself up as a transient window. In that case I'd actually argue it's wrong.

The relevant bit from ICCCM:

> The WM_TRANSIENT_FOR property (of type WINDOW) contains the ID of another top-level window. The implication is that this window is a pop-up on behalf of the named window, and window managers may decide not to decorate transient windows or may treat them differently in other ways.

Kfind isn't opened on behalf of anything else, it's a standalone application.

I don't think we should offer workarounds for this - clients should set their window properties properly, and most do.

**Comment by Kharacternyk** [comment] 2019-07-06 20:49
I've created a window rule that forces the window type of KFind to be "Normal Window" but it doesn't work. How does this script determine a "transient" window?

And about modules: I do agree that they are kind of dialogs. But I prefer the behavior when only the dialogs that pop-up from another window are not tiled. It's a bit weird when I launch a sys. set. module from krunner and it appears in the middle of the screen (moreover, I have removed all the shadows and borders and such a window looks just broken).

Can you suggest a workaround?

**Comment by faho** [comment] 2019-07-07 06:04
>How does this script determine a "transient" window?

By asking for the "transient" property. It's not really a window *type*.

Try `xprop` and click on the window, you'll see something like

>WM_TRANSIENT_FOR(WINDOW): window id # 0x4600008

which means it's a transient window for window 0x40600008. So you do `xprop -id 0x4600008`, and it'll tell you

>WM_NAME(STRING) = "Qt Client Leader Window"

So this is apparently a bogus window that just acts as the "leader", but doesn't actually have any geometry or icon or anything.

>Can you suggest a workaround?

No. Apparently this can't be adjusted via the window rules, but either way it should be fixed in kfind.

**Closed** 2019-07-07 06:08 UTC
Labels: enhancement

**Comment by faho** [comment] 2019-07-07 06:11
Okay, I added a workaround that tiles kfind regardless of window type or transient property. This will also tile any actual transient windows or dialogs (the help window for instance), but it appears it doesn't use them much.

KFind should still be fixed.

**Comment by Kharacternyk** [comment] 2019-07-07 11:43
It is tiled now, thanks!

**Comment by piotr-dobrogost** [comment] 2019-07-21 16:51
[The file dialog fails to implement X11 WM_TRANSIENT_FOR correctly](https://bugs.kde.org/show_bug.cgi?id=367699) is somehow related. I asked there if KFind should be treated like dialog or not.

**Comment by piotr-dobrogost** [comment] 2019-07-21 19:47
I guess there should be a way to force tiling for specific windows the same way there is a list of forced floating windows currently.

**Comment by faho** [comment] 2019-07-21 20:00
>I guess there should be a way to force tiling for specific windows the same way there is a list of forced floating windows currently.

Clients that claim to be "normal" windows, but can't resize are a dime a dozen, which is why we have the blacklist.  But clients that claim to be "not-normal" but could almost don't exist. This is because the cause for not tiling properly for the most part is not adding the stuff that would aid tiling wms - either resize functionality, or setting the window class to a non-default. The cause for floating too much would be making a client that resizes properly and *then* setting the window class to a non-default (or adding another floating signifier). I can't off-hand come up with a single case where this happens.

Just fix the client (since resizing is the hard part and it already has that this should be simple), and you'll have helped all tiling wms.

Also floating mistakenly isn't much of a problem, especially for us - KWin is a fully functional floating WM.
