### ISSUE TITLE
Title Bars Disappearing

### ISSUE THREAD

**Issue by c0lored** [kwin-scripts/kwin-tiling#120] opened 2018-12-20 21:37 UTC
The script was running really well, but it freaked out on a no name application, and my title bars disappeared. Removing and reinstalling script doesn't help. No window rules or application rules are being applied to anything, yet i have to run "kwin --replace" to get them back. Any ideas?

**Comment by faho** [comment] 2018-12-22 09:00
If you run `kwin --replace` in the terminal, what does it say? Are there any errors?

**Comment by faho** [comment] 2019-01-07 16:30
@c0lored: Ping?

**Comment by c0lored** [comment] 2019-01-12 02:51
Hey,
   Sorry about the delayed response. I will give it a try again Monday
(this was on my work machine) and see what I come up with. For the time
being I went to KDE +i3 and its pretty splendid, so I am not entirely sure
I would consider going back to kwin. With that being said, you software is
awesome and works, for the most part, wonderfully.

**Comment by osphost** [comment] 2019-02-09 16:22
Hi, I can report that I am experiencing this issue when I run VLC media player.
As soon as I try to resize the window etc all title bars disappear. 

VLC: 3.0.6-1
Distro: Manjaro KDE Plasma 5

`kwin_x11 --replace` seems to bring the title bars back, but the tiling script is not enabled.

**Comment by laloch** [comment] 2019-04-17 19:42
Disappearing title bars/borders usually mean that KWin crashed completely.
@osphost : Is this still an issue with the latest release or the current master/HEAD? I can confirm that VLC behaves very strangely, but that only affects its own window.

**Comment by faho** [comment] 2020-12-17 18:02
Yeah, we haven't been able to reproduce this one, and it looks like a kwin crash, closing!

**Closed by faho** 2020-12-17 18:02 UTC
Labels: needs-more-info
