### ISSUE TITLE
Move window to another screen is not working

### ISSUE THREAD

**Issue by indaleto** [kwin-scripts/kwin-tiling#262] opened 2022-06-25 08:12 UTC
Hi, I have multiple monitors and multiple tiled windows in one screen but I can't move one of them to next/previous screen with a shortcut. I've defined shift + ctrl + left/right in kwin to move window to previous/left screen but that does not work, unless the window is maximized.

I have the option Window Behaviour -> Separate screen focus checked, but uncheking does not work either.

Is there something I can do? thanks

Using Arch + KDE

**Edit**: After some tweeks (?) I can move windows to the left but not to the right!

**Comment by Dennis-Rall** [comment] 2022-07-11 13:40
I have the same problem. How did you get moving to the left screen working?

**Comment by faho** [comment] 2022-07-27 10:11
Duplicate of #88. Multimonitor needs work, and it needs work from someone who uses it.

**Closed by faho** 2022-07-27 10:11 UTC
