### ISSUE TITLE
Layout changes not "sticking"

### ISSUE THREAD

**Issue by TransAMrit** [kwin-scripts/kwin-tiling#242] opened 2021-03-02 19:31 UTC
When using Meta+Shift+PgUp, Meta+Shift+PgDown, or Meta+Shift+R, the expected layout changes takes effect, but unexpectedly reverts about a second later.

kwin-tiling version a240b4327892305008525fed96f9f9227c904893 and kwin-5.19.4.

**Comment by faho** [comment] 2021-03-05 17:00
I can't reproduce this, please check your logs for any output.

E.g. if you're using systemd, you can check them with `journalctl -f /usr/bin/kwin_x11` (or presumably kwin_wayland). If not you'll have to run `kwin_x11 --replace` in the terminal and see what that outputs.

Then try to switch layout and see what happens.

**Comment by faho** [comment] 2021-03-13 19:22
Closing for lack of information.

**Closed by faho** 2021-03-13 19:22 UTC
Labels: needs-more-info
