### ISSUE TITLE
Screen locker is tiling

### ISSUE THREAD

**Issue by pangwalla** [kwin-scripts/kwin-tiling#244] opened 2021-05-31 16:50 UTC
Hi, have been playing with this and can't seem to find a work-around.  Each time my screen locks using the default screen locker (using KDE Plasma under a Wayland session), the screen locker window tiles (e.g. if two windows were open on the desktop, the screenlocker will take up the upper right 1/4 of the screen only).

Have tried adding a few lines to the ignored.js file and updating the script to see if that helps including
```
ignored._ignoredlist = [
       ...
       "org.freedesktop.ScreenSaver",
       ...
]
```

Updated using 
```
plasmapkg2 -t kwinscript -u . 
```

Thanks!

**Comment by faho** [comment] 2021-06-01 16:57
I can confirm, but honestly that's better solved upstream. There's no reason for any script ever to apply to the screenlocker, and it should especially not be possible for it to make other content shine through.

Also:

>Have tried adding a few lines to the ignored.js file and updating the script to see if that helps including

What you would do here is to add that to your *configuration*, not the actual source.

-----------

Anyway, closing since it's a KWin bug.

**Closed by faho** 2021-06-01 16:57 UTC

**Comment by piotr-dobrogost** [comment] 2021-06-02 09:35
I filed https://bugs.kde.org/show_bug.cgi?id=437984
