### ISSUE TITLE
No config options

### ISSUE THREAD

**Issue by yaroedi** [kwin-scripts/kwin-tiling#79] opened 2017-02-19 14:09 UTC
I'm trying to use this script under plasma 5.9.2. I managed to install it and it seems to be working fine, except for the fact that there is no settings option and I can't get into the GUI. Anyone else having this problem?

Edit by @laloch: The solution is documented in the [Troubleshooting section](https://github.com/kwin-scripts/kwin-tiling#troubleshooting) of the README.

**Comment by drupol** [comment] 2017-02-19 17:27
Same here under gentoo.

**Comment by faho** [comment] 2017-02-19 22:24
I know that there was a similar issue a while back with Fedora that boiled down to wrong packaging.

Do you have any other scripts that do show configuration settings? Do you have `/usr/lib/qt/plugins/kwin/effects/configs/kcm_kwin4_genericscripted.so`? Or do you have a similarly named file in another directory?

**Comment by drupol** [comment] 2017-02-19 23:25
I have it in:

```
 ls -la /usr/lib/qt5/plugins/kwin/effects/configs/kcm_kwin4_genericscripted.so                                                         Mon 20 Feb 2017 12:24:25 AM CET
-rwxr-xr-x 1 root root 563760 Feb 15 10:06 /usr/lib/qt5/plugins/kwin/effects/configs/kcm_kwin4_genericscripted.so*

```

**Comment by faho** [comment] 2017-02-19 23:39
That should work - the corresponding line in metadata.desktop is

```
X-KDE-Library=kwin/effects/configs/kcm_kwin4_genericscripted
```

So if it is relative to /usr/lib/qt5/plugins in your case, it should be found. I don't know how the default qt plugin path is set, but you could try setting $QT_PLUGIN_PATH to "/usr/lib/qt5/plugins" and then launch `kwin_x11 --replace`.

**Comment by drupol** [comment] 2017-02-19 23:56
Nope, it doesn't work...

![screenshot_20170220_005622](https://cloud.githubusercontent.com/assets/252042/23108047/684e225e-f707-11e6-92e8-3f2b844220a0.png)

**Comment by yaroedi** [comment] 2017-02-21 10:38
Same here. Although I kind of worked around it by manually specifying options in ~/.config/kwinrc

**Comment by wcerfgba** [comment] 2017-03-11 12:38
I too cannot access the config options through 'KWin Scripts'.
I am running openSUSE Tumbleweed, and installed kwin-tiling through the 'KWin Scripts' screen, not from git.
My genericscripted is at `/usr/lib64/qt5/plugins/kwin/effects/configs/kcm_kwin4_genericscripted.so`.
@yaroedi Could you please share how you configured in kwinrc?

**Comment by yaroedi** [comment] 2017-03-11 12:47
@wcerfgba Sure, here you go:

Under `[Plugins]`, make sure it's enabled with `kwin-script-tilingEnabled=true`.

And then, for the plugin itself:
```
[Script-kwin-script-tiling]
fullscreenGaps=true
gapSize=4
screenGapSizeBottom=8
screenGapSizeLeft=8
screenGapSizeRight=8
screenGapSizeTop=8
windowsGapSizeHeight=4
windowsGapSizeWidth=4
```
But I haven't quite worked out the layouting stuff yet.... ;)

**Comment by tillschaefer** [comment] 2017-05-09 19:46
i can also confirm the problem. Running kwin_x11 --replace with the correct plugin path also did not solve the problem. Furthermore, there is the videowall plugin for witch the config option is present. It also uses `X-KDE-Library=kwin/effects/configs/kcm_kwin4_genericscripted` Thus, I do not think it is a problem with the plugin path.

**Comment by xenithorb** [comment] 2017-05-10 14:16
I too have no config options in Fedora 25 - Plasma 5.9.5

**Comment by drupol** [comment] 2017-05-10 14:20
I ended up by disabling it as I couldn't configure it properly 👎

**Comment by faho** [comment] 2017-05-10 14:44
So, I have just downloaded the KDE spin of Fedora 25 and started it live in virtualbox. I then installed the script via GHNS, activated it and clicked the config button. The menu appeared.

Is there anything I'm missing? @xenithorb: Did you do anything differently, e.g. install via a different spin? Netinstall?

@tillschaefer: 

>KWin spits out these errors here (I do not know if it is related):
file:///home/till/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilelist.js:353: TypeError: Cannot call method 'readConfig' of undefined

Are you using Plasma 5 or 4? That looks like it's 4, which is no longer supported.

**Comment by tillschaefer** [comment] 2017-05-10 14:50
I am using the latest stable releases: 
- Plasma 5.9.5
- Frameworks 5.33 
- KDE Applications 17.04.0 
- Qt 5.7.1 + 4.8.7 (slotted install) 

However, this is an upgrade installation (i.e. Plasma 4 was installed some time ago). Maybe some Plasma 4 configuration persisted after the upgrade?

**Comment by xenithorb** [comment] 2017-05-10 15:32
Did you upgrade your virtual machine? The live media isn't updated over the course of the release, and by now it has become quite out date. @faho 

I have the same Plasma and Kf5 and Qt versions as @tillschaefer, though my Kapps is more out-of-date. This was originally a KDE spin install but it's been updated through 3 versions of Fedora so who knows.

**Comment by faho** [comment] 2017-05-10 17:09
Okay, I upgraded my VM and it is indeed broken. The button doesn't even show up. Unfortunately, `systemsettings5` in a konsole doesn't print any useful errors, so I have no idea what to do. (At first it prints stuff about not finding the correct .desktop file for the service type, but even after renaming the file it still won't show the menu)

It's possible it's related to Qt5 being 5.7.1 (mine is 5.8.0). Since I don't think anyone here wants to compile their entire desktop anew, we're gonna have to wait on that.

**Comment by bahhumbug** [comment] 2017-05-20 05:46
I don't think QT 5.8.0 will solve this as I'm unable to access the configuration using that version (archlinux).

* plasma 5.9.5
* plasma framework 5.34
* qt 5.8.0

**Comment by VinegarLove** [comment] 2017-05-24 17:41
Configuration not present for me too.
Same system as bahhumbug

**Comment by TomBZombie** [comment] 2017-05-26 18:14
FYI it works on Arch Linux installed via AUR package https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kwin-scripts-tiling

**Comment by AnotherBugworm** [comment] 2017-05-27 12:01
@TomBZombie this is what I have on arch with package from AUR
![image](https://cloud.githubusercontent.com/assets/7214361/26521287/343cbdf4-42ed-11e7-880c-0b86da2451fc.png)

**Comment by TomBZombie** [comment] 2017-05-27 12:04
Interesting, here's what I get: 

![image](https://cloud.githubusercontent.com/assets/2454540/26521299/efbfa6d8-42dc-11e7-8da1-084a11e2b48d.png)

I'm on plasma 5.9.5.

**Comment by AnotherBugworm** [comment] 2017-05-27 12:13
@TomBZombie works for me on other user as well, but if you delete it and install again(or create a new user), it won't work anymore

**Comment by timlepes** [comment] 2017-06-17 00:38
I am having the same problem described by AnotherBugworm...  I get the error "Plugin does not provide configuration file in expected location" when trying to configure it in system settings.  I see that there is a file located at /usr/share/kwin/scripts/kwin-scripts-tilling/content/config/main.xml just like the video-wall plug-in (.../videowall/content/config/main.xml).  The video wall configuration from system settings works (does not give error).  I am using Arch on x86_64 with kernel 4.11.5-1-ARCH, running  KDE 5.35.0 / Plasma 5.10.2.  Uninstalling then re-installing the script does not fix the problem.  Ideas?

**Comment by jonnyrobbie** [comment] 2017-06-25 20:28
Yeah, chiming in with the same problem. Latest Arch, installed through KDE store the plugin doesn't offer the setting button. Installing the script from AUR, there is a button, but it errors out with that unprovided location message.

**Comment by TomBZombie** [comment] 2017-06-25 21:07
Try following the instructions in the README.md:

```
git clone https://github.com/faho/kwin-tiling.git
cd kwin-tiling/
plasmapkg2 --type kwinscript -i .
```

That worked for me on my laptop. AUR: No config options,  installed as above; worked as expected.

**Comment by tpnx** [comment] 2017-06-27 08:11
Hi there,

I have the same problems in KDE neon 5.10.2. I tried all the tipps in this Issue, but I am not able to get the config menu running.

ATM I configured the gapps directly in kwinrc. Is there a documentation of all settings?

Regards
tpnx

**Comment by dsmorozov** [comment] 2017-06-27 08:34
I've faces the issue on latest Arch as well. This fixes the issue in a moment:
`cd /usr/share/kservicetypes5 &&
sudo ln -s kwinscript.desktop kwin-script.desktop`

**Comment by tpnx** [comment] 2017-06-27 09:04
Thanks,

unfortunately it doesn't work for me.

**Comment by BenoitZugmeyer** [comment] 2017-06-27 19:48
I managed to get the configuration button on Arch Linux!

It seems that the kwin script needs to be a known KDE service to get a "Configuration" button (see  the condition to show the button [here](https://github.com/KDE/kcmutils/blob/560c0b50e8c9c304cb7ebee9da08de182986f964/src/kpluginselector.cpp#L740) and [here](https://github.com/KDE/kcmutils/blob/560c0b50e8c9c304cb7ebee9da08de182986f964/src/kpluginselector.cpp#L495-L496)). But installing the script via the `systemsettings` interface or by using the `plasmapkg2` utility does *not* register the script as a KDE service. To do this manually, you have to put the script `metadata.desktop` in either `~/.local/share/kservices5` or `/usr/share/kservices5`, example:

```
mkdir -p ~/.local/share/kservices5
cp ~/.local/share/kwin/scripts/kwin-script-tiling/metadata.desktop ~/.local/share/kservices5/kwin-script-tiling.desktop
```

I have no idea if there is a way to do this via a command. Also I guess we should open an issue somewhere in the KDE bug tracker but I feel so ignorant how all this should work.

I hope it works for you.

**Comment by tpnx** [comment] 2017-06-28 07:50
Works!

Thank you so much!

**Comment by drupol** [comment] 2017-06-28 07:59
Works too, thanks!

**Comment by BoltsJ** [comment] 2017-07-09 23:26
Following @BenoitZugmeyer's instructions gets the configuration window to appear, but it is missing the layout and excluded window class sections. Running KDE Neon User Edition.
 ![screenshot_20170709_182026](https://user-images.githubusercontent.com/182554/27998361-529d9392-64d3-11e7-8ab4-b4304d0d8cd4.png)

**Comment by faho** [comment] 2017-07-12 09:37
Urgh... yeah.

The issue there is that the widget we used (KEditListWidget) has been removed, and AFAIK there's no great replacement. The best we can do is probably QLineEdit, which requires users to enter it as a comma-separated string.

I've now made that change in 3658cc1. This might require that you open up the config UI because (for some reason) this is now stored as `class1\\,class2`, ie. the "," is backslash-escaped.

**Comment by JackKiefer** [comment] 2017-08-21 00:16
Running KDE Neon with Plasma version 5.10.4. With the most recent version of the repo I ran into this same issue but was able to fix it per @BenoitZugmeyer 's instructions! :)

**Comment by copyme** [comment] 2017-09-06 11:33
@faho I think that it would be nice to add the solution of @BenoitZugmeyer into the documentation.

**Comment by arusahni** [comment] 2018-08-22 11:35
@copyme I filed a PR with @BenoitZugmeyer's fix: #107

**Comment by OvermindDL1** [comment] 2018-11-09 16:12
@BenoitZugmeyer method fixed it here in the latest KDE Neon as well, any chance on having the Makefile copy that file there itself when `install`ing?

**Comment by ShayBox** [comment] 2019-02-14 17:33
Tried installing via git, the built-in Get scripts button, and both AUR packages, using the instructions provided on the README to make a folder and symlink, but none have gotten the settings page to show up, the closest I've gotten is the AUR package, will show the button but is missing something so it won't open it.

**Comment by Aetf** [comment] 2019-03-30 21:04
> The issue there is that the widget we used (KEditListWidget) has been removed, and AFAIK there's no great replacement. The best we can do is probably QLineEdit, which requires users to enter it as a comma-separated string.

Just FYI, `KEditListWidget` is still available, but you need an additional package ([`kdesignerplugin`](https://github.com/KDE/kdesignerplugin)) installed in system for `QUiLoader` to be able to create it when dynamically creating the configuration interface.

I'm facing the same issue in my [script](https://Aetf/kwin-maxmize-to-new-desktop). After installing `kdesignerplugin`, the configuration works as intended. (My system is ArchLinux)

**Comment by faho** [comment] 2019-03-30 21:13
>     

Just FYI, KEditListWidget is still available, but you need an additional package (kdesignerplugin) 

@Aetf: Thanks for the information. So IMHO that's still an "effectively not available" since we can't specify these dependencies from the script or get a good error.

**Comment by piotr-dobrogost** [comment] 2019-03-31 17:28
The issue raised here has been reported by LinG on 2017-11-03 as KDE bug [386509](https://bugs.kde.org/show_bug.cgi?id=386509) with no action taken so far :(

**Comment by nedimAT** [comment] 2019-07-29 18:12
> I managed to get the configuration button on Arch Linux!
> 
> It seems that the kwin script needs to be a known KDE service to get a "Configuration" button (see the condition to show the button [here](https://github.com/KDE/kcmutils/blob/560c0b50e8c9c304cb7ebee9da08de182986f964/src/kpluginselector.cpp#L740) and [here](https://github.com/KDE/kcmutils/blob/560c0b50e8c9c304cb7ebee9da08de182986f964/src/kpluginselector.cpp#L495-L496)). But installing the script via the `systemsettings` interface or by using the `plasmapkg2` utility does _not_ register the script as a KDE service. To do this manually, you have to put the file `metadata.desktop` in either `~/.local/share/kservices5` or `/usr/share/kservices5`, example:
> 
> ```
> mkdir -p ~/.local/share/kservices5
> cp ~/.local/share/kwin/scripts/kwin-script-tiling/metadata.desktop ~/.local/share/kservices5/kwin-script-tiling.desktop
> ```
> 
> I have no idea if there is a way to do this via a command. Also I guess we should open an issue somewhere in the KDE bug tracker but I feel so ignorant how all this should work.
> 
> I hope it works for you.

isn't the "correct" way a symlink? Like:
`ln -s ~/.local/share/kwin/scripts/kwin-script-tiling/metadata.desktop ~/.local/share/kwin/scripts/kwin-script-tiling/kwin-scripting-tiling.desktop`

**Comment by laloch** [comment] 2019-07-29 18:19
> isn't the "correct" way a symlink? Like:
> `ln -s ~/.local/share/kwin/scripts/kwin-script-tiling/metadata.desktop ~/.local/share/kwin/scripts/kwin-script-tiling/kwin-scripting-tiling.desktop`

Yes, the [Troubleshooting](https://github.com/kwin-scripts/kwin-tiling#troubleshooting) section of the README does, indeed, suggests a symlink rather than a copy. The location (`~/.local/share/kservices5`) is, however, correct.

**Comment by faho** [comment] 2020-08-07 12:10
As far as I can see this is a problem with kpackagetool/whatever the thing is called now.

Nothing to fix here, so I'm closing.

**Closed by faho** 2020-08-07 12:10 UTC

**Comment by ehamawy** [comment] 2022-04-07 04:35
The commands in "Enabling User-Configuration" in the guide still don't make the settings button appear. Latest KDE Plasma on PopOS

**Comment by ruby232** [comment] 2022-04-10 02:08
The commands in "Enabling User-Configuration" in the guide still don't make the settings button appear. Latest KDE Plasma on Ubuntu 21.10

**Comment by faho** [comment] 2022-04-10 06:00
Nothing we can do about that, file bugs upstream.
