### ISSUE TITLE
Gaps break shortcuts

### ISSUE THREAD

**Issue by halbGefressen** [kwin-scripts/kwin-tiling#173] opened 2019-07-18 12:50 UTC
Hi, I just installed the script and edited the config a bit. Before editing everything worked as it should. However, after changing the gap size between windows the up/down shortcuts also resized the focused windows from left to right. Does anyone have an idea why?

**Comment by Kharacternyk** [comment] 2019-07-18 13:40
Can confirm. If a window doesn't have any space at the top/bottom, trying to resize it in vertical direction changes it's width. In my case, width shrinks by few pixels. I have 8-pixels gaps, if it does matter.

**Comment by faho** [comment] 2019-07-18 13:49
Duplicate of #111.

**Closed by faho** 2019-07-18 13:49 UTC
